spring:
  application:
    name: preppilot-backend
  profiles:
    active:
      - dev

  jwt:
  secret: mySecretKey
  expiration: 86400000



  datasource:
    url: jdbc:postgresql://localhost:5432/preppilot
    username: postgres
    password: Dha@2023
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true




server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include:  health,info
logging:
  level:
    root: info
    com.preppilot: DEBUG
  pattern:
    console: "%d %-5level [%thread] %logger : %msg%n"